### ISSUE TITLE
Pixiv 反代问题

### ISSUE THREAD

**Issue by sxjeru** [Samarium150/mirai-console-lolicon#61]
即使 config 中设置了 `proxy: i.pixiv.re` ，其仍然获取到 `i.pixiv.cat` 相关的地址，而该域名已被墙。

![image](https://user-images.githubusercontent.com/20513115/145701237-5aca0e17-d8e2-4f2d-87be-78d7a59c9290.png)

**Comment by Samarium150** [comment]
可以先设置个网络代理，我研究一下是哪儿的bug

**Comment by Samarium150** [comment]
试试把配置文件里的`proxy`改为
```yaml
proxy: 'https://i.pixiv.re'
```

**Comment by sxjeru** [comment]
可用，感谢回复！

**Comment by SnowMoonSS** [comment]
如下，`proxy: 'https://i.pixiv.re'`后仍然使用`https://i.pixiv.cat`
```
2021-12-30 19:10:24 I/Lolicon: request body: {"r18":0,"num":1,"uid":[],"keyword":"","tag":[],"size":["original"],"proxy":"https://i.pixiv.re","dataAfter":null,"dataBefore":null,"dsc":null}
2021-12-30 19:10:24 V/Bot.Bot的QQ号: master的QQ昵称(master的QQ号) -> 涩图 来一张
2021-12-30 19:10:26 I/Lolicon: {"error":"","data":[{"pid":71611685,"p":0,"uid":10552397,"title":"おなペット妹","author":"kanju","r18":false,"width":1000,"height":1412,"tags":["オリジナル","原创","
猫耳","cat ears","ロリ","萝莉","C95"],"ext":"jpg","uploadDate":1541939046000,"urls":{"original":"https://i.pixiv.cat/img-original/img/2018/11/11/21/24/06/71611685_p0.jpg"}}]}
2021-12-30 19:10:26 V/Bot.Bot的QQ号: Friend(master的QQ号) <- 标题: おなペット妹\n作者: kanju (uid: 10552397)\n标签: [オリジナル, 原创, 猫耳, cat ears, ロリ, 萝莉, C95]\n链接: https://pixiv.net/artworks/71611685
2021-12-30 19:10:46 E/Lolicon: io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://i.pixiv.cat/img-original/img/2018/11/11/21/24/06/71611685_p0.jpg, connect_timeout=unknown ms]
io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://i.pixiv.cat/img-original/img/2018/11/11/21/24/06/71611685_p0.jpg, connect_timeout=unknown ms]
        at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:183)
        at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:75)
        at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1)
        at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:39)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:510)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        ... 3 more
```

**Comment by SnowMoonSS** [comment]
> 如下，`proxy: 'https://i.pixiv.re'`后仍然使用`https://i.pixiv.cat`
> 
> ```
> 2021-12-30 19:10:24 I/Lolicon: request body: {"r18":0,"num":1,"uid":[],"keyword":"","tag":[],"size":["original"],"proxy":"https://i.pixiv.re","dataAfter":null,"dataBefore":null,"dsc":null}
> 2021-12-30 19:10:24 V/Bot.Bot的QQ号: master的QQ昵称(master的QQ号) -> 涩图 来一张
> 2021-12-30 19:10:26 I/Lolicon: {"error":"","data":[{"pid":71611685,"p":0,"uid":10552397,"title":"おなペット妹","author":"kanju","r18":false,"width":1000,"height":1412,"tags":["オリジナル","原创","
> 猫耳","cat ears","ロリ","萝莉","C95"],"ext":"jpg","uploadDate":1541939046000,"urls":{"original":"https://i.pixiv.cat/img-original/img/2018/11/11/21/24/06/71611685_p0.jpg"}}]}
> 2021-12-30 19:10:26 V/Bot.Bot的QQ号: Friend(master的QQ号) <- 标题: おなペット妹\n作者: kanju (uid: 10552397)\n标签: [オリジナル, 原创, 猫耳, cat ears, ロリ, 萝莉, C95]\n链接: https://pixiv.net/artworks/71611685
> 2021-12-30 19:10:46 E/Lolicon: io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://i.pixiv.cat/img-original/img/2018/11/11/21/24/06/71611685_p0.jpg, connect_timeout=unknown ms]
> io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://i.pixiv.cat/img-original/img/2018/11/11/21/24/06/71611685_p0.jpg, connect_timeout=unknown ms]
>         at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:183)
>         at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:75)
>         at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1)
>         at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:39)
>         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:510)
>         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
>         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
>         at java.base/java.lang.Thread.run(Thread.java:829)
> Caused by: java.net.SocketTimeoutException: connect timed out
>         at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
>         at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
>         at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
>         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
>         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>         at java.base/java.net.Socket.connect(Socket.java:609)
>         at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119)
>         at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
>         at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195)
>         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
>         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
>         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
>         at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
>         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
>         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
>         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
>         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
>         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
>         at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
>         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
>         ... 3 more
> ```

是最新的5.0.0 beta6

**Comment by Samarium150** [comment]
> > 如下，`proxy: 'https://i.pixiv.re'`后仍然使用`https://i.pixiv.cat`
> > ```
> > 2021-12-30 19:10:24 I/Lolicon: request body: {"r18":0,"num":1,"uid":[],"keyword":"","tag":[],"size":["original"],"proxy":"https://i.pixiv.re","dataAfter":null,"dataBefore":null,"dsc":null}
> > 2021-12-30 19:10:24 V/Bot.Bot的QQ号: master的QQ昵称(master的QQ号) -> 涩图 来一张
> > 2021-12-30 19:10:26 I/Lolicon: {"error":"","data":[{"pid":71611685,"p":0,"uid":10552397,"title":"おなペット妹","author":"kanju","r18":false,"width":1000,"height":1412,"tags":["オリジナル","原创","
> > 猫耳","cat ears","ロリ","萝莉","C95"],"ext":"jpg","uploadDate":1541939046000,"urls":{"original":"https://i.pixiv.cat/img-original/img/2018/11/11/21/24/06/71611685_p0.jpg"}}]}
> > 2021-12-30 19:10:26 V/Bot.Bot的QQ号: Friend(master的QQ号) <- 标题: おなペット妹\n作者: kanju (uid: 10552397)\n标签: [オリジナル, 原创, 猫耳, cat ears, ロリ, 萝莉, C95]\n链接: https://pixiv.net/artworks/71611685
> > 2021-12-30 19:10:46 E/Lolicon: io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://i.pixiv.cat/img-original/img/2018/11/11/21/24/06/71611685_p0.jpg, connect_timeout=unknown ms]
> > io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://i.pixiv.cat/img-original/img/2018/11/11/21/24/06/71611685_p0.jpg, connect_timeout=unknown ms]
> >         at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:183)
> >         at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:75)
> >         at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1)
> >         at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:39)
> >         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:510)
> >         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> >         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> >         at java.base/java.lang.Thread.run(Thread.java:829)
> > Caused by: java.net.SocketTimeoutException: connect timed out
> >         at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
> >         at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
> >         at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
> >         at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
> >         at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> >         at java.base/java.net.Socket.connect(Socket.java:609)
> >         at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:119)
> >         at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:283)
> >         at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:195)
> >         at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:249)
> >         at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:108)
> >         at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:76)
> >         at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
> >         at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
> >         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> >         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
> >         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> >         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
> >         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> >         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
> >         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
> >         at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
> >         at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
> >         ... 3 more
> > ```
> 
> 是最新的5.0.0 beta6

试试把https去掉

**Comment by SnowMoonSS** [comment]
啊这……去掉`https://`之后出现了这个bug
后台看过了，连`download`文件夹都没有……
```bash
$ ~/n/d/io.github.samarium150.mirai.plugin.mirai-console-lolicon> ls -al
total 12
drwxrwxr-x  2 qqbot qqbot 4096 Dec 30 23:27 ./
drwxrwxr-x 15 qqbot qqbot 4096 Dec 31 00:08 ../
-rw-rw-r--  1 qqbot qqbot  578 Dec 31 00:59 Data.yml
```
```
2021-12-31 00:42:06 V/Bot.Bot的QQ号: master的昵称(master的QQ号) -> 涩图 来一张
2021-12-31 00:42:07 I/Lolicon: {"error":"","data":[{"pid":89269572,"p":0,"uid":22628045,"title":"是需要调教的刻晴","author":"糖tou","r18":false,"width":1500,"height":1500,"tags":["原神","Genshin Impact","高品質パンツ","高品质内裤","魅惑の谷間","魅惑的乳沟","丁字裤","揉みしだきたい乳","诱人把玩的乳房","刻晴","Keqing","拘束","束缚","ツインテール","双马尾"],"ext":"jpg","uploadDate":1618853555000,"urls":{"original":"https://i.pixiv.re/img-original/img/2021/04/20/02/32/35/89269572_p0.jpg"}}]}
2021-12-31 00:42:07 V/Bot.Bot的QQ号: Friend(master的QQ号) <- 标题: 是需要调教的刻晴\n作者: 糖tou (uid: 22628045)\n标签: [原神, Genshin Impact, 高品質パンツ, 高品质内裤, 魅惑の谷間, 魅惑的乳沟, 丁字裤, 揉みしだきたい乳, 诱人把玩的乳房, 刻晴, Keqing, 拘束, 束缚, ツインテール, 双马尾]\n链接: https://pixiv.net/artworks/89269572
2021-12-31 00:42:10 E/Lolicon: java.io.FileNotFoundException: /data/io.github.samarium150.mirai.plugin.mirai-console-lolicon/download/89269572_p0.jpg (No such file or directory)
java.io.FileNotFoundException: /data/io.github.samarium150.mirai.plugin.mirai-console-lolicon/download/89269572_p0.jpg (No such file or directory)
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
        at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
        at io.github.samarium150.mirai.plugin.util.RequestHandlerKt.downloadImage(RequestHandler.kt:62)
        at io.github.samarium150.mirai.plugin.util.RequestHandlerKt$downloadImage$1.invokeSuspend(RequestHandler.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by Samarium150** [comment]
> 啊这……去掉`https://`之后出现了这个bug
> 后台看过了，连`download`文件夹都没有……
> ```bash
> $ ~/n/d/io.github.samarium150.mirai.plugin.mirai-console-lolicon> ls -al
> total 12
> drwxrwxr-x  2 qqbot qqbot 4096 Dec 30 23:27 ./
> drwxrwxr-x 15 qqbot qqbot 4096 Dec 31 00:08 ../
> -rw-rw-r--  1 qqbot qqbot  578 Dec 31 00:59 Data.yml
> ```
> ```
> 2021-12-31 00:42:06 V/Bot.Bot的QQ号: master的昵称(master的QQ号) -> 涩图 来一张
> 2021-12-31 00:42:07 I/Lolicon: {"error":"","data":[{"pid":89269572,"p":0,"uid":22628045,"title":"是需要调教的刻晴","author":"糖tou","r18":false,"width":1500,"height":1500,"tags":["原神","Genshin Impact","高品質パンツ","高品质内裤","魅惑の谷間","魅惑的乳沟","丁字裤","揉みしだきたい乳","诱人把玩的乳房","刻晴","Keqing","拘束","束缚","ツインテール","双马尾"],"ext":"jpg","uploadDate":1618853555000,"urls":{"original":"https://i.pixiv.re/img-original/img/2021/04/20/02/32/35/89269572_p0.jpg"}}]}
> 2021-12-31 00:42:07 V/Bot.Bot的QQ号: Friend(master的QQ号) <- 标题: 是需要调教的刻晴\n作者: 糖tou (uid: 22628045)\n标签: [原神, Genshin Impact, 高品質パンツ, 高品质内裤, 魅惑の谷間, 魅惑的乳沟, 丁字裤, 揉みしだきたい乳, 诱人把玩的乳房, 刻晴, Keqing, 拘束, 束缚, ツインテール, 双马尾]\n链接: https://pixiv.net/artworks/89269572
> 2021-12-31 00:42:10 E/Lolicon: java.io.FileNotFoundException: /data/io.github.samarium150.mirai.plugin.mirai-console-lolicon/download/89269572_p0.jpg (No such file or directory)
> java.io.FileNotFoundException: /data/io.github.samarium150.mirai.plugin.mirai-console-lolicon/download/89269572_p0.jpg (No such file or directory)
>         at java.base/java.io.FileOutputStream.open0(Native Method)
>         at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
>         at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
>         at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
>         at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
>         at io.github.samarium150.mirai.plugin.util.RequestHandlerKt.downloadImage(RequestHandler.kt:62)
>         at io.github.samarium150.mirai.plugin.util.RequestHandlerKt$downloadImage$1.invokeSuspend(RequestHandler.kt)
>         at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
>         at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
>         at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
> ```

发个新的issue吧，我之后看看

**Comment by SnowMoonSS** [comment]
最新的5.2.1，`proxy: i.pixiv.re`，但看日志似乎使用的还是`i.pixiv.cat`……
```
2022-02-23 18:32:27 V/Bot.1234567890: Friend(123456789) <- [mirai:quote:[3101],[-707510250]]正在获取图片...
2022-02-23 18:32:27 I/Lolicon: request body: {"r18":0,"num":1,"uid":[],"keyword":"","tag":[],"size":["regular"],"proxy":"i.pixiv.re","dataAfter":null,"dataBefore":null,"dsc":null}
2022-02-23 18:32:28 I/Lolicon: {"error":"","data":[{"pid":94023719,"p":0,"uid":3051808,"title":"マリ?","author":"ウシミッツ","r18":false,"width":751,"height":1370,"tags":["ブ
ルアカ","ブル?ア?カイブ","碧蓝档案","伊落マリ?","Mari Iochi","マイクロビキニ","极小比基尼","おへそ","肚脐","剥ぎ取りたいブラ","让人想脱掉的胸罩","剥ぎ取りたいパンツ","让人
想脱掉的内裤","性?者","sexy priest","?上の?乳","极上贫乳"],"ext":"jpg","uploadDate":1636449815000,"urls":{"regular":"https://i.pixiv.cat/img-master/img/2021/11/09/18/23/35/94023719_p0_master1200.jpg"}}]}
2022-02-23 18:32:28 V/Bot.3011567668: Friend(123456789) <- 标题: マリ?\n作者: ウシミッツ (uid: 3051808)\n标签: [ブルアカ, ブル?ア?カイブ, 碧蓝档案, 伊落マリ?, Mari Iochi, 
マイクロビキニ, 极小比基尼, おへそ, 肚脐, 剥ぎ取りたいブラ, 让人想脱掉的胸罩, 剥ぎ取りたいパンツ, 让人想脱掉的内裤, 性?者, sexy priest, ?上の?乳, 极上贫乳]\n链接: https://pixiv.net/artworks/94023719
2022-02-23 18:32:38 E/Lolicon: io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://i.pixiv.cat/img-master/img/2021/11/09/18/23/35/94023719_p0_master1200.jpg, connect_timeout=unknown ms]
io.ktor.network.sockets.ConnectTimeoutException: Connect timeout has expired [url=https://i.pixiv.cat/img-master/img/2021/11/09/18/23/35/94023719_p0_master1200.jpg, connect_timeout=unknown ms]
        at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException(HttpTimeout.kt:183)
        at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(OkUtils.kt:77)
        at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(OkUtils.kt:1)
        at io.ktor.client.engine.okhttp.OkHttpCallback.onFailure(OkUtils.kt:39)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:525)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        ... 3 more
```

**Comment by Samarium150** [comment]
> 最新的5.2.1，`proxy: i.pixiv.re`，但看日志似乎使用的还是`i.pixiv.cat`……

这个bug非常神秘，你试试把`https`加上
```yaml
proxy: "https://i.pixiv.re"
```

**Comment by SnowMoonSS** [comment]
> > 最新的5.2.1，`proxy: i.pixiv.re`，但看日志似乎使用的还是`i.pixiv.cat`……
> 
> 这个bug非常神秘，你试试把`https`加上
> 
> ```yaml
> proxy: "https://i.pixiv.re"
> ```

草，它好起来了。太神秘了
