### ISSUE TITLE
尝试合并转发消息时导致qsing服务崩溃

### ISSUE THREAD

**Issue by XokoukioX** [Samarium150/mirai-console-lolicon#94]
### 问题描述

发送指令后 控制端报错且qsign崩溃

### 复现

/lolicon get tag

### mirai-console 版本

2.14.0

### 插件版本

6.0.8

### 日志

```text
2024-02-08 19:41:50 V/Bot.2580769182: 江风 ( ) -> /lolicon get 
2024-02-08 19:41:50 I/Lolicon: request body: {"r18":0,"num":1,"uid":[],"keyword":"","tag":[["Shi "]],"size":["regular"],"proxy":"https://i.pixiv.re","dataAfter":null,"dataBefore":null,"dsc":null}
2024-02-08 19:41:54 W/Lolicon: Exception in executing command `[mirai:source:ids=[22387], internalIds=[49792492], from friend 19823 85 to 2580 182 at 17073 2511]/lolicon get Shi a`
 command owned by Lolicon v6.0.8 with Friend(198 485)
java.util.concurrent.ExecutionException: java.net.SocketException: Connection reset
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:210)
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.sign(UnidbgFetchQsign.kt:190)
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.qSecurityGetSign(UnidbgFetchQsign.kt:173)
        at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.buildRawUniPacket(OutgoingPacket.kt:139)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbSendMsg.createToFriendImpl$mirai_core(MessageSvc.PbSendMsg.kt:694)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvc_PbSendMsgKt.createToFriend(MessageSvc.PbSendMsg.kt:564)
        at net.mamoe.mirai.internal.message.protocol.outgoing.FriendMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:82)
        at net.mamoe.mirai.internal.message.protocol.outgoing.FriendMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:71)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.process(GeneralMessageSenderProtocol.kt:66)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:287)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:364)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoing(MessageProtocolFacade.kt:348)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.preprocessAndSendOutgoing(MessageProtocolFacade.kt)
        at net.mamoe.mirai.internal.contact.AbstractUserKt.sendMessageImpl(AbstractUser.kt:263)
        at net.mamoe.mirai.internal.contact.FriendImpl.sendMessage(FriendImpl.kt:102)
        at net.mamoe.mirai.console.command.FriendCommandSender.sendMessage$suspendImpl(CommandSender.kt:671)
        at net.mamoe.mirai.console.command.FriendCommandSender.sendMessage(CommandSender.kt)
        at mirai-console-lolicon-6.0.8.mirai2.jar//io.github.samarium150.mirai.plugin.lolicon.util.GeneralUtilKt.getNotificationReceipt(GeneralUtil.kt:55)
        at mirai-console-lolicon-6.0.8.mirai2.jar//io.github.samarium150.mirai.plugin.lolicon.command.Lolicon.get(Lolicon.kt:90)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
        at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
        at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
        at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
        at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invokeSuspend(CommandReflector.kt:339)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1.invoke(CommandReflector.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call$suspendImpl(CommandSignature.kt:84)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureFromKFunctionImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:168)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$suspendImpl(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand$default(CommandManager.kt:126)
        at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain.handleCommand(PluginMain.kt:98)
        at chat-command-0.6.0.mirai2.jar//net.mamoe.mirai.console.plugins.chat.command.PluginMain$onEnable$2$1.invokeSuspend(PluginMain.kt:66)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:254)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)

2024-02-08 19:42:14 V/Bot.2580769182: 是LuckyE！哒‭ #C95F3D(3282076201) -> 6
>
2024-02-08 19:42:43 V/Bot.2580769182: 是LuckyE！哒‭ #C95F3D(3282076201) -> 6
2024-02-08 19:42:44 V/Bot.2580769182: Event: BotOfflineEvent.Dropped(bot=Bot(2580769182), cause=xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'First use must be submitted with android_id and guid.', reconnect=true)
2024-02-08 19:42:44 W/Bot.2580769182: Connection lost, reconnecting... (xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'First use must be submitted with android_id and guid.')
2024-02-08 19:42:44 V/Bot.2580769182: Event: BotOfflineEvent.Dropped(bot=Bot(2580769182), cause=xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'First use must be submitted with android_id and guid.', reconnect=true)
2024-02-08 19:42:44 W/Bot.2580769182: Connection lost, reconnecting... (xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'First use must be submitted with android_id and guid.')
2024-02-08 19:42:44 I/Bot.2580769182: Reconnected successfully in 0.005s.
2024-02-08 19:42:44 V/Bot.2580769182: Event: BotOfflineEvent.Dropped(bot=Bot(2580769182), cause=xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'First use must be submitted with android_id and guid.', reconnect=true)
2024-02-08 19:42:44 W/Bot.2580769182: Connection lost, reconnecting... (xyz.cssxsh.mirai.tool.KFCStateException: unidbg-fetch-qsign 服务异常, 请检查其日志, 'First use must be submitted with android_id and guid.')
2024-02-08 19:42:45 I/UnidbgFetchQsign: Bot(258 182) initialize by http://127.0.0.1:13579
2024-02-08 19:42:47 I/UnidbgFetchQsign: Bot(258  2) register, Instance loaded successfully.
2024-02-08 19:42:47 I/UnidbgFetchQsign: Bot(258 2) initialize complete
2024-02-08 19:42:47 I/Bot.2580769182: Reconnected successfully in 3.026s.
2024-02-08 19:42:48 I/Bot.2580769182: Saved account secrets to local cache for fast login.
2024-02-08 19:42:48 I/Bot.2580769182: Login successful.
2024-02-08 19:42:48 V/Bot.2580769182: Event: BotOnlineEvent(bot=Bot(258 ))
2024-02-08 19:42:48 V/Bot.2580769182: Event: BotReloginEvent(bot=Bot(2580 2), cause=null)
2024-02-08 19:42:48 I/Bot.2580769182: Reconnected successfully in 3.56s.
2024-02-08 19:42:50 V/Bot.2580769182: 是LuckyE！哒‭ #C95F3D(328 1) -> 6
2024-02-08 19:42:52 V/Bot.2580769182: Friend(32820 1) <- It seems you've entered "6" again. If there's a specific question or topic you'd like to discuss, feel free to provide more information, and I'll do my best to assist you!
2024-02-08 19:43:52 I/Lolicon: request body: {"r18":0,"num":1,"uid":[],"keyword":"","tag":[["Shirasu"]],"size":["regular"],"proxy":"https://i.pixiv.re","dataAfter":null,"dataBefore":null,"dsc":null}
2024-02-08 19:43:52 V/Bot.2580769182: 江风裙下之臣(19 5) -> /lolicon get Shi sa
2024-02-08 19:43:53 V/Bot.2580769182: Friend(198 ) <- [mirai:quote:[mirai:source:ids=[22388], internalIds=[366037042], from friend 198 5 to 25 2 at 1707 3], content=/lolicon get Shi usa]正在获取图片...
2024-02-08 19:43:54 I/Lolicon: {"error":"","data":[{"pid":112216127,"p":0,"uid":43965828,"title":"🏖️","author":"monoco55","r18":false,"width":2334,"height":4096,"tags":["ブルアカ","下江コハル","白洲アズサ","Shirasu Azusa","阿慈 谷ヒフミ","Ajitani Hifumi","浦和ハナコ","Urawa Hanako","ブルーアーカイブ"," 碧蓝档案","海","sea","水着","泳装","海水浴","swimming in the sea","後ろの存 在感"],"ext":"jpg","aiType":1,"uploadDate":1696237517000,"urls":{"regular":"https://i.pixiv.re/img-master/img/2023/10/02/18/05/17/112216127_p0_master1200.jpg"}}]}
2024-02-08 19:44:01 W/Lolicon: Exception in executing command `[mirai:source:ids=[22388], internalIds=[366037042], from friend 1982  to 25  at 170 ]/lolicon get Shirasu Azusa`
 command owned by Lolicon v6.0.8 with Friend(19 )
java.util.concurrent.ExecutionException: java.net.SocketException: Connection reset
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//org.asynchttpclient.netty.NettyResponseFuture.get(NettyResponseFuture.java:210)
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.sign(UnidbgFetchQsign.kt:190)
        at fix-protocol-version-1.13.0.mirai2.jar//xyz.cssxsh.mirai.tool.UnidbgFetchQsign.qSecurityGetSign(UnidbgFetchQsign.kt:173)
        at net.mamoe.mirai.internal.network.protocol.packet.OutgoingPacketKt.buildRawUniPacket(OutgoingPacket.kt:139)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvcPbSendMsg.createToFriendImpl$mirai_core(MessageSvc.PbSendMsg.kt:694)
        at net.mamoe.mirai.internal.network.protocol.packet.chat.receive.MessageSvc_PbSendMsgKt.createToFriend(MessageSvc.PbSendMsg.kt:564)
        at net.mamoe.mirai.internal.message.protocol.outgoing.FriendMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:82)
        at net.mamoe.mirai.internal.message.protocol.outgoing.FriendMessageProtocolStrategy.createPacketsForGeneralMessage(MessageProtocolStrategy.kt:71)
        at net.mamoe.mirai.internal.message.protocol.impl.GeneralMessageSenderProtocol$GeneralMessageSender.process(GeneralMessageSenderProtocol.kt:66)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:26)
        at net.mamoe.mirai.internal.message.protocol.outgoing.OutgoingMessageProcessorAdapter.process(OutgoingMessagePipelineProcessor.kt:20)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process$suspendImpl(ProcessorPipeline.kt:287)
        at net.mamoe.mirai.internal.pipeline.AbstractProcessorPipeline.process(ProcessorPipeline.kt)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.preprocessAndSendOutgoingImpl(MessageProtocolFacade.kt:364)
        at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl$preprocessAndSendOutgoingImpl$1.invokeSuspend(MessageProtocolFacade.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:401)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:434)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:254)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1132)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:357)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:151)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at fix-protocol-version-1.13.0.mirai2.jar[private]//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Comment by Samarium150** [comment]
稳定复现还是偶尔出现
